/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAgentsWebhookRouteImport } from './routes/api/agents/webhook'
import { Route as ApiAgentsRegisterRouteImport } from './routes/api/agents/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsWebhookRoute = ApiAgentsWebhookRouteImport.update({
  id: '/api/agents/webhook',
  path: '/api/agents/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsRegisterRoute = ApiAgentsRegisterRouteImport.update({
  id: '/api/agents/register',
  path: '/api/agents/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/agents/webhook': typeof ApiAgentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/agents/webhook': typeof ApiAgentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/agents/register': typeof ApiAgentsRegisterRoute
  '/api/agents/webhook': typeof ApiAgentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/agents/register' | '/api/agents/webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/agents/register' | '/api/agents/webhook'
  id: '__root__' | '/' | '/api/agents/register' | '/api/agents/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAgentsRegisterRoute: typeof ApiAgentsRegisterRoute
  ApiAgentsWebhookRoute: typeof ApiAgentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/webhook': {
      id: '/api/agents/webhook'
      path: '/api/agents/webhook'
      fullPath: '/api/agents/webhook'
      preLoaderRoute: typeof ApiAgentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/register': {
      id: '/api/agents/register'
      path: '/api/agents/register'
      fullPath: '/api/agents/register'
      preLoaderRoute: typeof ApiAgentsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAgentsRegisterRoute: ApiAgentsRegisterRoute,
  ApiAgentsWebhookRoute: ApiAgentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
